### ISSUE TITLE
Move models.json into /models

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-example-offline-sync#13]
/to @bajtos @raymondfeng @seanbrookes

[From a previous discussion](https://github.com/strongloop/loopback-example-full-stack/issues/3#issuecomment-44499682)

>  There should be a convention for adding new things by adding a new file, without modifying any existing code. 

I really like this approach. I think we should adopt it for models as well. This would mean all model definitions would exist as `models/*.json`.

For this app it would look like:

```
/models
  /todo.json
  /todo.js
  /user.json
  ...
```

`todo.json` would be the typical `models.json` definition just in a separate file.

`todo.js` would be the extensions to the `todo` definition. One simplification we might want to do is the `todo.js` file could define the model by requiring the `todo.json` file.

``` js
// todo.js
var Todo = module.exports = loopback.PersistedModel.extend('Todo', require('./todo.json'));
```

This would close the gap between hand written models and generated models. There isn't a lot of boilerplate that we would have to generate either. We would have to generate the additional files. This should be simple to add to the workspace.

`.extend()` could support the definition format of `todo.json` without much modification.

**Comment by jbcpollak** [comment]
Sorry to revive an old ticket: I'm looking for best practices or an example of how to share models between  multiple server-side projects. The externalized projects @bajtos mentioned in his last post, like `example-full-stack-models` doesn't exist. I found [strong-mesh-models](https://github.com/strongloop/strong-mesh-models), but it seems to actually contain a full loopback server and export that, instead of just exporting the models.

Are external models possible?

**Comment by superkhau** [comment]
@jbcpollak Please create your own issue instead of reviving this old one. In addition, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
